FROM  frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD support-service-restful-0.0.1-SNAPSHOT.war app.war
#RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.war"]
EXPOSE 8761